# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a37aa3782ba251687f25d520c631b395c76fe2dac1052989a4f104181e83550f5ddbed56638a36637f1bef35c044e6c58fe029fa8f6b212e359c956f93ed8cf

test:
  secret_key_base: c8bb772ff88150e00d2209d399b59c6e51374d1e427c852803cce1bebab556af1fd31a88118a3d7c82355b7d8765cf8c79ed3dadf280fb87612945c544de0c2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
